spring:
  thymeleaf:
    # thymeleaf缓存关闭
    cache: false
  datasource:
    # 驱动
    driver-class-name: com.mysql.jdbc.Driver
    # mysql连接数据库
    url: jdbc:mysql://localhost:3306/community?useSSL=false
    # 账号
    username: root
    # 密码
    password: 123456
    # 数据库连接池类型
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最大连接数
      maximum-pool-size: 15
      # 最小空闲连接
      minimum-idle: 5
      # 超时时间
      idle-timeout: 30000

  main:
    allow-circular-references: true

mybatis:
  configuration:
    #将mybatis日志输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启mybatis的驼峰命名自动映射开关 a_colomn ---- aColomn
    map-underscore-to-camel-case: true
    #自动生成主键
    use-generated-keys: true

# ServletProperties
server:
  port: 8080
  servlet:
    context-path: /community

logging:
  level:
    com:
      zhuhai:
        community: debug

